package dev.himalay.ccms.views.welcome;

import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.dependency.Uses;
import com.vaadin.flow.component.html.H1;
import com.vaadin.flow.component.html.H2;
import com.vaadin.flow.component.html.H5;
import com.vaadin.flow.component.html.H6;
import com.vaadin.flow.component.html.Span;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.FlexComponent.JustifyContentMode;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.router.RouteAlias;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;
import com.vaadin.flow.theme.lumo.LumoUtility.Padding;
import dev.himalay.ccms.views.MainLayout;
import jakarta.annotation.security.PermitAll;

@PageTitle("Welcome")
@Route(value = "welcome", layout = MainLayout.class)
@RouteAlias(value = "", layout = MainLayout.class)
@PermitAll
@Uses(Icon.class)
public class WelcomeView extends Composite<VerticalLayout> {

    public WelcomeView() {
        VerticalLayout layoutColumn2 = new VerticalLayout();
        HorizontalLayout layoutRow = new HorizontalLayout();
        H2 h2 = new H2();
        HorizontalLayout layoutRow2 = new HorizontalLayout();
        VerticalLayout layoutColumn3 = new VerticalLayout();
        H6 h6 = new H6();
        H1 h1 = new H1();
        Span badge = new Span();
        VerticalLayout layoutColumn4 = new VerticalLayout();
        H6 h62 = new H6();
        H1 h12 = new H1();
        Span badge2 = new Span();
        HorizontalLayout layoutRow3 = new HorizontalLayout();
        VerticalLayout layoutColumn5 = new VerticalLayout();
        H6 h63 = new H6();
        H1 h13 = new H1();
        Span badge3 = new Span();
        VerticalLayout layoutColumn6 = new VerticalLayout();
        H6 h64 = new H6();
        H1 h14 = new H1();
        Span badge4 = new Span();
        HorizontalLayout layoutRow4 = new HorizontalLayout();
        VerticalLayout layoutColumn7 = new VerticalLayout();
        H6 h65 = new H6();
        H1 h15 = new H1();
        Span badge5 = new Span();
        VerticalLayout layoutColumn8 = new VerticalLayout();
        H6 h66 = new H6();
        H1 h16 = new H1();
        Span badge6 = new Span();
        HorizontalLayout layoutRow5 = new HorizontalLayout();
        H5 h5 = new H5();
        getContent().setWidth("100%");
        getContent().getStyle().set("flex-grow", "1");
        layoutColumn2.setWidth("100%");
        layoutColumn2.getStyle().set("flex-grow", "1");
        layoutRow.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutRow);
        layoutRow.addClassName(Gap.MEDIUM);
        layoutRow.addClassName(Padding.XSMALL);
        layoutRow.setWidth("100%");
        layoutRow.getStyle().set("flex-grow", "1");
        h2.setText("DASHBOARD");
        h2.setWidth("max-content");
        layoutRow2.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutRow2);
        layoutRow2.addClassName(Gap.MEDIUM);
        layoutRow2.setWidth("100%");
        layoutRow2.setHeight("min-content");
        layoutColumn3.setHeightFull();
        layoutRow2.setFlexGrow(1.0, layoutColumn3);
        layoutColumn3.getStyle().set("flex-grow", "1");
        layoutColumn3.setHeight("100%");
        layoutColumn3.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutColumn3.setAlignItems(Alignment.CENTER);
        h6.setText("CASES");
        h6.setWidth("max-content");
        h1.setText("1,111");
        h1.setWidth("max-content");
        badge.setText("+20%");
        badge.setWidth("min-content");
        badge.getElement().getThemeList().add("badge");
        layoutColumn4.setHeightFull();
        layoutRow2.setFlexGrow(1.0, layoutColumn4);
        layoutColumn4.setWidth("100%");
        layoutColumn4.getStyle().set("flex-grow", "1");
        layoutColumn4.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutColumn4.setAlignItems(Alignment.CENTER);
        h62.setText("USERS");
        h62.setWidth("max-content");
        h12.setText("50");
        h12.setWidth("max-content");
        badge2.setText("Badge");
        badge2.setWidth("min-content");
        badge2.getElement().getThemeList().add("badge");
        layoutRow3.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutRow3);
        layoutRow3.addClassName(Gap.MEDIUM);
        layoutRow3.setWidth("100%");
        layoutRow3.getStyle().set("flex-grow", "1");
        layoutColumn5.setHeightFull();
        layoutRow3.setFlexGrow(1.0, layoutColumn5);
        layoutColumn5.getStyle().set("flex-grow", "1");
        layoutColumn5.setHeight("100%");
        layoutColumn5.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutColumn5.setAlignItems(Alignment.CENTER);
        h63.setText("SLA NEARING");
        h63.setWidth("max-content");
        h13.setText("20");
        h13.setWidth("max-content");
        badge3.setText("-5%");
        badge3.setWidth("min-content");
        badge3.getElement().getThemeList().add("badge");
        layoutColumn6.setHeightFull();
        layoutRow3.setFlexGrow(1.0, layoutColumn6);
        layoutColumn6.setWidth("100%");
        layoutColumn6.getStyle().set("flex-grow", "1");
        layoutColumn6.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutColumn6.setAlignItems(Alignment.CENTER);
        h64.setText("DEpartments");
        h64.setWidth("max-content");
        h14.setText("10");
        h14.setWidth("max-content");
        badge4.setText("Badge");
        badge4.setWidth("min-content");
        badge4.getElement().getThemeList().add("badge");
        layoutRow4.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutRow4);
        layoutRow4.addClassName(Gap.MEDIUM);
        layoutRow4.setWidth("100%");
        layoutRow4.getStyle().set("flex-grow", "1");
        layoutColumn7.setHeightFull();
        layoutRow4.setFlexGrow(1.0, layoutColumn7);
        layoutColumn7.getStyle().set("flex-grow", "1");
        layoutColumn7.getStyle().set("flex-grow", "1");
        layoutColumn7.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutColumn7.setAlignItems(Alignment.CENTER);
        h65.setText("next hearing dates");
        h65.setWidth("max-content");
        h15.setText("15");
        h15.setWidth("max-content");
        badge5.setText("Badge");
        badge5.setWidth("min-content");
        badge5.getElement().getThemeList().add("badge");
        layoutColumn8.setHeightFull();
        layoutRow4.setFlexGrow(1.0, layoutColumn8);
        layoutColumn8.setWidth("100%");
        layoutColumn8.getStyle().set("flex-grow", "1");
        layoutColumn8.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutColumn8.setAlignItems(Alignment.CENTER);
        h66.setText("reminders sent");
        h66.setWidth("max-content");
        h16.setText("200");
        h16.setWidth("max-content");
        badge6.setText("Badge");
        badge6.setWidth("min-content");
        badge6.getElement().getThemeList().add("badge");
        layoutRow5.addClassName(Gap.MEDIUM);
        layoutRow5.addClassName(Padding.MEDIUM);
        layoutRow5.setWidth("100%");
        layoutRow5.setHeight("min-content");
        h5.setText("Footer");
        h5.setWidth("max-content");
        getContent().add(layoutColumn2);
        layoutColumn2.add(layoutRow);
        layoutRow.add(h2);
        layoutColumn2.add(layoutRow2);
        layoutRow2.add(layoutColumn3);
        layoutColumn3.add(h6);
        layoutColumn3.add(h1);
        layoutColumn3.add(badge);
        layoutRow2.add(layoutColumn4);
        layoutColumn4.add(h62);
        layoutColumn4.add(h12);
        layoutColumn4.add(badge2);
        layoutColumn2.add(layoutRow3);
        layoutRow3.add(layoutColumn5);
        layoutColumn5.add(h63);
        layoutColumn5.add(h13);
        layoutColumn5.add(badge3);
        layoutRow3.add(layoutColumn6);
        layoutColumn6.add(h64);
        layoutColumn6.add(h14);
        layoutColumn6.add(badge4);
        layoutColumn2.add(layoutRow4);
        layoutRow4.add(layoutColumn7);
        layoutColumn7.add(h65);
        layoutColumn7.add(h15);
        layoutColumn7.add(badge5);
        layoutRow4.add(layoutColumn8);
        layoutColumn8.add(h66);
        layoutColumn8.add(h16);
        layoutColumn8.add(badge6);
        getContent().add(layoutRow5);
        layoutRow5.add(h5);
    }
}
