package dev.himalay.ccms.views.addnewcase;

import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.combobox.MultiSelectComboBox;
import com.vaadin.flow.component.datepicker.DatePicker;
import com.vaadin.flow.component.dependency.Uses;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.formlayout.FormLayout.ResponsiveStep;
import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.html.Hr;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.FlexComponent.JustifyContentMode;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.select.Select;
import com.vaadin.flow.component.textfield.EmailField;
import com.vaadin.flow.component.textfield.TextArea;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;
import com.vaadin.flow.theme.lumo.LumoUtility.Padding;
import dev.himalay.ccms.views.MainLayout;
import jakarta.annotation.security.RolesAllowed;
import java.util.ArrayList;
import java.util.List;

@PageTitle("Add New Case")
@Route(value = "addcase", layout = MainLayout.class)
@RolesAllowed("ADMIN")
@Uses(Icon.class)
public class AddNewCaseView extends Composite<VerticalLayout> {

    public AddNewCaseView() {
        VerticalLayout layoutColumn2 = new VerticalLayout();
        HorizontalLayout layoutRow = new HorizontalLayout();
        H3 h3 = new H3();
        HorizontalLayout layoutRow2 = new HorizontalLayout();
        FormLayout formLayout2Col = new FormLayout();
        MultiSelectComboBox multiSelectComboBox = new MultiSelectComboBox();
        ComboBox comboBox = new ComboBox();
        Select select = new Select();
        Select select2 = new Select();
        Hr hr = new Hr();
        VerticalLayout layoutColumn3 = new VerticalLayout();
        H3 h32 = new H3();
        HorizontalLayout layoutRow3 = new HorizontalLayout();
        FormLayout formLayout3Col = new FormLayout();
        TextField textField = new TextField();
        ComboBox comboBox2 = new ComboBox();
        TextField textField2 = new TextField();
        ComboBox comboBox3 = new ComboBox();
        ComboBox comboBox4 = new ComboBox();
        TextField textField3 = new TextField();
        TextField textField4 = new TextField();
        DatePicker datePicker = new DatePicker();
        TextField textField5 = new TextField();
        DatePicker datePicker2 = new DatePicker();
        DatePicker datePicker3 = new DatePicker();
        HorizontalLayout layoutRow4 = new HorizontalLayout();
        TextArea textArea = new TextArea();
        Hr hr2 = new Hr();
        VerticalLayout layoutColumn4 = new VerticalLayout();
        HorizontalLayout layoutRow5 = new HorizontalLayout();
        H3 h33 = new H3();
        FormLayout formLayout3Col2 = new FormLayout();
        ComboBox comboBox5 = new ComboBox();
        TextField textField6 = new TextField();
        TextField textField7 = new TextField();
        Hr hr3 = new Hr();
        VerticalLayout layoutColumn5 = new VerticalLayout();
        HorizontalLayout layoutRow6 = new HorizontalLayout();
        H3 h34 = new H3();
        FormLayout formLayout2Col2 = new FormLayout();
        ComboBox comboBox6 = new ComboBox();
        TextField textField8 = new TextField();
        EmailField emailField = new EmailField();
        TextField textField9 = new TextField();
        Hr hr4 = new Hr();
        HorizontalLayout layoutRow7 = new HorizontalLayout();
        Button buttonPrimary = new Button();
        Button buttonTertiary = new Button();
        getContent().setWidth("100%");
        getContent().setHeight("min-content");
        layoutColumn2.setWidthFull();
        getContent().setFlexGrow(1.0, layoutColumn2);
        layoutColumn2.addClassName(Padding.SMALL);
        layoutColumn2.setWidth("100%");
        layoutColumn2.setHeight("min-content");
        layoutColumn2.setJustifyContentMode(JustifyContentMode.START);
        layoutColumn2.setAlignItems(Alignment.START);
        layoutRow.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutRow);
        layoutRow.addClassName(Gap.MEDIUM);
        layoutRow.setWidth("100%");
        layoutRow.setHeight("min-content");
        h3.setText("User Details:");
        h3.setWidth("max-content");
        layoutRow2.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutRow2);
        layoutRow2.addClassName(Gap.MEDIUM);
        layoutRow2.addClassName(Padding.SMALL);
        layoutRow2.setWidth("100%");
        layoutRow2.setHeight("min-content");
        formLayout2Col.setWidth("100%");
        multiSelectComboBox.setLabel("SELECT USERS");
        multiSelectComboBox.setWidth("min-content");
        setMultiSelectComboBoxSampleData(multiSelectComboBox);
        comboBox.setLabel("SELECT USER TYPE (Petitioner / Respondant)");
        comboBox.setWidth("min-content");
        setComboBoxSampleData(comboBox);
        select.setLabel("SELECT RESPONDANT");
        select.setWidth("min-content");
        setSelectSampleData(select);
        select2.setLabel("RESPONDANT LAWYER");
        select2.setWidth("min-content");
        setSelectSampleData(select2);
        layoutColumn3.setWidthFull();
        getContent().setFlexGrow(1.0, layoutColumn3);
        layoutColumn3.setWidth("100%");
        layoutColumn3.setHeight("min-content");
        h32.setText("Case Details:");
        h32.setWidth("max-content");
        layoutRow3.setWidthFull();
        layoutColumn3.setFlexGrow(1.0, layoutRow3);
        layoutRow3.addClassName(Gap.MEDIUM);
        layoutRow3.setWidth("100%");
        layoutRow3.getStyle().set("flex-grow", "1");
        formLayout3Col.setWidth("100%");
        formLayout3Col.setResponsiveSteps(new ResponsiveStep("0", 1), new ResponsiveStep("250px", 2),
                new ResponsiveStep("500px", 3));
        textField.setLabel("CASE NO");
        textField.setWidth("min-content");
        comboBox2.setLabel("CASE TYPE");
        comboBox2.setWidth("min-content");
        setComboBoxSampleData(comboBox2);
        textField2.setLabel("CASE SUBTYPE");
        textField2.setWidth("min-content");
        comboBox3.setLabel("CASE PRIORITY");
        comboBox3.setWidth("min-content");
        setComboBoxSampleData(comboBox3);
        comboBox4.setLabel("CASE STAGE");
        comboBox4.setWidth("min-content");
        setComboBoxSampleData(comboBox4);
        textField3.setLabel("CASE STATUS");
        textField3.setWidth("min-content");
        textField4.setLabel("FILING NUMBER");
        textField4.setWidth("min-content");
        datePicker.setLabel("FILING DATE");
        datePicker.getStyle().set("flex-grow", "1");
        textField5.setLabel("REGISTRATION NUMBER");
        textField5.setWidth("min-content");
        datePicker2.setLabel("Registration Date");
        datePicker2.getStyle().set("flex-grow", "1");
        datePicker3.setLabel("Next Hearing Date");
        datePicker3.getStyle().set("flex-grow", "1");
        layoutRow4.setWidthFull();
        layoutColumn3.setFlexGrow(1.0, layoutRow4);
        layoutRow4.addClassName(Gap.MEDIUM);
        layoutRow4.setWidth("100%");
        layoutRow4.getStyle().set("flex-grow", "1");
        textArea.setLabel("Description");
        textArea.setWidth("100%");
        layoutColumn4.setWidthFull();
        getContent().setFlexGrow(1.0, layoutColumn4);
        layoutColumn4.setWidth("100%");
        layoutColumn4.getStyle().set("flex-grow", "1");
        layoutRow5.setWidthFull();
        layoutColumn4.setFlexGrow(1.0, layoutRow5);
        layoutRow5.addClassName(Gap.MEDIUM);
        layoutRow5.setWidth("100%");
        layoutRow5.getStyle().set("flex-grow", "1");
        h33.setText("Court Details:");
        h33.setWidth("max-content");
        formLayout3Col2.setWidth("100%");
        formLayout3Col2.setResponsiveSteps(new ResponsiveStep("0", 1), new ResponsiveStep("250px", 2),
                new ResponsiveStep("500px", 3));
        comboBox5.setLabel("Court Type");
        comboBox5.getStyle().set("flex-grow", "1");
        setComboBoxSampleData(comboBox5);
        textField6.setLabel("Court Name");
        textField6.getStyle().set("flex-grow", "1");
        textField7.setLabel("Judge Name");
        textField7.getStyle().set("flex-grow", "1");
        layoutColumn5.setWidthFull();
        getContent().setFlexGrow(1.0, layoutColumn5);
        layoutColumn5.setWidth("100%");
        layoutColumn5.getStyle().set("flex-grow", "1");
        layoutRow6.setWidthFull();
        layoutColumn5.setFlexGrow(1.0, layoutRow6);
        layoutRow6.addClassName(Gap.MEDIUM);
        layoutRow6.setWidth("100%");
        layoutRow6.getStyle().set("flex-grow", "1");
        h34.setText("Advocate Details:");
        h34.setWidth("max-content");
        formLayout2Col2.setWidth("100%");
        comboBox6.setLabel("Lawyer Type");
        comboBox6.getStyle().set("flex-grow", "1");
        setComboBoxSampleData(comboBox6);
        textField8.setLabel("Lawyer Name");
        textField8.getStyle().set("flex-grow", "1");
        emailField.setLabel("Email");
        emailField.setWidth("min-content");
        textField9.setLabel("Phone Number");
        textField9.setWidth("min-content");
        layoutRow7.setWidthFull();
        getContent().setFlexGrow(1.0, layoutRow7);
        layoutRow7.addClassName(Gap.MEDIUM);
        layoutRow7.addClassName(Padding.SMALL);
        layoutRow7.setWidth("100%");
        layoutRow7.getStyle().set("flex-grow", "1");
        layoutRow7.setAlignItems(Alignment.CENTER);
        layoutRow7.setJustifyContentMode(JustifyContentMode.START);
        buttonPrimary.setText("Save");
        layoutRow7.setAlignSelf(FlexComponent.Alignment.CENTER, buttonPrimary);
        buttonPrimary.setWidth("min-content");
        buttonPrimary.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        buttonTertiary.setText("Cancel");
        buttonTertiary.setWidth("min-content");
        buttonTertiary.addThemeVariants(ButtonVariant.LUMO_TERTIARY);
        getContent().add(layoutColumn2);
        layoutColumn2.add(layoutRow);
        layoutRow.add(h3);
        layoutColumn2.add(layoutRow2);
        layoutRow2.add(formLayout2Col);
        formLayout2Col.add(multiSelectComboBox);
        formLayout2Col.add(comboBox);
        formLayout2Col.add(select);
        formLayout2Col.add(select2);
        getContent().add(hr);
        getContent().add(layoutColumn3);
        layoutColumn3.add(h32);
        layoutColumn3.add(layoutRow3);
        layoutRow3.add(formLayout3Col);
        formLayout3Col.add(textField);
        formLayout3Col.add(comboBox2);
        formLayout3Col.add(textField2);
        formLayout3Col.add(comboBox3);
        formLayout3Col.add(comboBox4);
        formLayout3Col.add(textField3);
        formLayout3Col.add(textField4);
        formLayout3Col.add(datePicker);
        formLayout3Col.add(textField5);
        formLayout3Col.add(datePicker2);
        formLayout3Col.add(datePicker3);
        layoutColumn3.add(layoutRow4);
        layoutRow4.add(textArea);
        getContent().add(hr2);
        getContent().add(layoutColumn4);
        layoutColumn4.add(layoutRow5);
        layoutRow5.add(h33);
        layoutColumn4.add(formLayout3Col2);
        formLayout3Col2.add(comboBox5);
        formLayout3Col2.add(textField6);
        formLayout3Col2.add(textField7);
        layoutColumn4.add(hr3);
        getContent().add(layoutColumn5);
        layoutColumn5.add(layoutRow6);
        layoutRow6.add(h34);
        layoutColumn5.add(formLayout2Col2);
        formLayout2Col2.add(comboBox6);
        formLayout2Col2.add(textField8);
        formLayout2Col2.add(emailField);
        formLayout2Col2.add(textField9);
        layoutColumn5.add(hr4);
        getContent().add(layoutRow7);
        layoutRow7.add(buttonPrimary);
        layoutRow7.add(buttonTertiary);
    }

    record SampleItem(String value, String label, Boolean disabled) {
    }

    private void setMultiSelectComboBoxSampleData(MultiSelectComboBox multiSelectComboBox) {
        List<SampleItem> sampleItems = new ArrayList<>();
        sampleItems.add(new SampleItem("first", "First", null));
        sampleItems.add(new SampleItem("second", "Second", null));
        sampleItems.add(new SampleItem("third", "Third", Boolean.TRUE));
        sampleItems.add(new SampleItem("fourth", "Fourth", null));
        multiSelectComboBox.setItems(sampleItems);
        multiSelectComboBox.setItemLabelGenerator(item -> ((SampleItem) item).label());
    }

    private void setComboBoxSampleData(ComboBox comboBox) {
        List<SampleItem> sampleItems = new ArrayList<>();
        sampleItems.add(new SampleItem("first", "First", null));
        sampleItems.add(new SampleItem("second", "Second", null));
        sampleItems.add(new SampleItem("third", "Third", Boolean.TRUE));
        sampleItems.add(new SampleItem("fourth", "Fourth", null));
        comboBox.setItems(sampleItems);
        comboBox.setItemLabelGenerator(item -> ((SampleItem) item).label());
    }

    private void setSelectSampleData(Select select) {
        List<SampleItem> sampleItems = new ArrayList<>();
        sampleItems.add(new SampleItem("first", "First", null));
        sampleItems.add(new SampleItem("second", "Second", null));
        sampleItems.add(new SampleItem("third", "Third", Boolean.TRUE));
        sampleItems.add(new SampleItem("fourth", "Fourth", null));
        select.setItems(sampleItems);
        select.setItemLabelGenerator(item -> ((SampleItem) item).label());
        select.setItemEnabledProvider(item -> !Boolean.TRUE.equals(((SampleItem) item).disabled()));
    }
}
